### ISSUE TITLE
Home vs Tazama

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [tazama-lf/tazama-lf.github.io#1]
Suggest to replace the "HOME" text in the menu bar with TAZAMA (using the Tazama logo, if possible).

Now:

![image](https://github.com/tazama-lf/tazama-lf.github.io/assets/123470803/76b71526-3c49-4098-b47a-b9f652e2bca5)

Proposed:

![image](https://github.com/tazama-lf/tazama-lf.github.io/assets/123470803/b9b09124-587c-4b3c-884b-6a16351134d1)

**Comment by hythloda** [comment]
please review this and see if it is good.
