### ISSUE TITLE
Hyperlink and highlight color

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [tazama-lf/tazama-lf.github.io#3]
For menu highlights and hyperlinks, set the highlight colour to the Tazama flower colour:

HTML code #51BE99

![image](https://github.com/tazama-lf/tazama-lf.github.io/assets/123470803/97dbd7b5-6996-4a12-9d14-37063d10cdd7)

**Comment by hythloda** [comment]
Fixed!
